### ISSUE TITLE
Arc A series configuration issue about export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/ipex-llm#10153] opened 2024-02-18 06:50 UTC
set this config, the latency of chatGLM3-6b's next token became slower from 20.4ms to 34.5ms with 1k input prompt, 512 token size.
<class 'transformers_modules.modeling_chatglm.ChatGLMForConditionalGeneration'>
=========First token cost 4.1437 s and 5.5625 GB=========
=========Rest tokens cost average 0.0208 s (159 tokens in all) and 5.5625 GB=========
=========First token cost 0.3410 s and 5.5625 GB=========
=========Rest tokens cost average 0.0204 s (159 tokens in all) and 5.5625 GB=========
export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1, the result is as below:
<class 'transformers_modules.modeling_chatglm.ChatGLMForConditionalGeneration'>
=========First token cost 4.1536 s and 5.5625 GB=========
=========Rest tokens cost average 0.0350 s (159 tokens in all) and 5.5625 GB=========
=========First token cost 0.3509 s and 5.5625 GB=========
=========Rest tokens cost average 0.0347 s (159 tokens in all) and 5.5625 GB=========

**Comment by hkvision** [comment] 2024-02-19 01:51
Same issue as https://github.com/intel-analytics/BigDL/issues/10133
This issue further detects the issue is impacted by SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS only.
We will look into this in your environment.

**Comment by hkvision** [comment] 2024-02-19 08:34
Can reproduce this issue on this machine, the differences:
- driver version: https://dgpu-docs.intel.com/releases/stable_775_20_20231219.html VS https://dgpu-docs.intel.com/releases/stable_647_21_20230714.html (ours)
- CPU: Intel(R) Xeon(R) w5-3435X VS 13th Gen Intel(R) Core(TM) i9-13900K (ours)

**Comment by hkvision** [comment] 2024-04-02 11:17
Fixed in: https://github.com/intel-analytics/ipex-llm/pull/10566

**Closed by hkvision** 2024-04-02 11:17 UTC
Labels: user issue
