### ISSUE TITLE
Google gemma models has much lower accuracy than their accuracy of Open LLM leaderboard

### ISSUE THREAD

**Issue by yzha107** [intel-analytics/ipex-llm#11472] opened 2024-07-01 05:28 UTC
Hi, 

We have run three Google gemma models with Winogrande on MTL or LNL, and we got much lower accuracy than Open LLM leaderboard. The detailed data as below:

Model | Precision | Device | Transformer Ver. | Acc.  [Winogrande] | Leaderboard   reference | % acc.   Degradation
-- | -- | -- | -- | -- | -- | --
google/gemma-7b-it | sym_int4 | MTL | 4.38.1 | 0.528 | 0.6796 (float16) | 25.11%
google/gemma-7b-it | fp8 | MTL | 4.38.1 | 0.5391 | 0.6796 (float16) | 23.06%
google/codegemma-7b-it | sym_int4 | LNL | 4.38.2 | 0.5217 | 0.6622 (float16) | 23.74%
google/codegemma-7b-it | fp8 | LNL | 4.38.2 | 0.5478 | 0.6622 (float16) | 18.91%
google/gemma-2b-it | sym_int4 | LNL | 4.38.2 | 0.5478 | 0.6093 (float16) | 10.63%
google/gemma-2b-it | fp8 | LNL | 4.38.2 | 0.5454 | 0.6093 (float16) | 11.07%

Thanks,
Yi

**Comment by lalalapotter** [comment] 2024-07-02 03:03
Hi @yzha107 , could you please provide some details of your experiments, such as running scripts and environment configuration (you can use this script to check the environment: https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/scripts), so that we can reproduce it.

**Comment by lalalapotter** [comment] 2024-07-02 07:41
Hi @yzha107 , After following tests:

- Test setting
ipex-llm: 2.1.0b20240701
transformers：4.38.2
scripts：https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/dev/benchmark/harness

- Test steps
```shell
# run.sh
source /opt/intel/oneapi/setvars.sh --force

python run_llb.py --model hf-causal-experimental --pretrained /path/to/model --precision fp16 --device xpu --tasks winogrande --batch 1 --no_cache --model_args "trust_remote_code=True"
```

- Test results

  | Precision | Winogrande |
-- | -- | -- 
gemma-2b-it | fp16 | 0.5383 |
codegemma-7b-it | fp16 | 0.5343 |
gemma-7b-it | fp16 | 0.532 |

- Summary
  - The quantized model with `sym_int4/fp8` precision provided by ipex-llm has no obvious accuracy drop compared to the fp16 model.
  - The fp16 model results is based on the open source framework (https://github.com/EleutherAI/lm-evaluation-harness) , which cannot reproduce the results of huggingface leaderboard. There may be differences and incompatibilities between the open source framework and huggingface leaderboard.
  
We recommend that you first try to reproduce the leaderboard results using the fp16 model, and then use the quantized model.

**Comment by yzha107** [comment] 2024-07-02 08:15
Hi @lalalapotter,

Thanks for the response. We tried the fp16 precision first and it failed with OOM. We also used the harness scripts (https://github.com/EleutherAI/lm-evaluation-harness) and winogrande dataset. The test machine is `Meteor Lake, U7-155H, 32GB`. So we compared the sym_int4/f8 precision with the float 16 precision result on huggingface leaderboard.

So as you mean, the gemma models' accuracy differences with huggingface leaderbord is due to the test framework difference and incompatibilities, right?

Thanks,
Yi

**Comment by lalalapotter** [comment] 2024-07-02 08:18
> Hi @lalalapotter,
> 
> Thanks for the response. We tried the fp16 precision first and it failed with OOM. We also used the harness scripts (https://github.com/EleutherAI/lm-evaluation-harness) and winogrande dataset. The test machine is `Meteor Lake, U7-155H, 32GB`. So we compared the sym_int4/f8 precision with the float 16 precision result on huggingface leaderboard.
> 
> So as you mean, the gemma models' accuracy differences with huggingface leaderbord is due to the test framework difference and incompatibilities, right?
> 
> Thanks, Yi

Yes, it is.

**Comment by lalalapotter** [comment] 2024-07-10 00:22
Close the issue for now, if you have any updates please reach out.

**Closed by lalalapotter** 2024-07-10 00:22 UTC
Labels: user issue
